# -*- coding: utf-8 -*-
"""eda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f5jx6VS9huCjczC3I3Mq18aqdkrkywY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data
df = pd.read_csv('/content/financial_loan.csv')

# First look
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

# Data types and missing values
print("Data Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nMissing Value Percentage:")
print(round(df.isnull().sum() / len(df) * 100, 2))

# Fix date columns
date_cols = ['issue_date', 'last_credit_pull_date', 'last_payment_date', 'next_payment_date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col])

# Fill missing emp_title with 'Unknown'
df['emp_title'] = df['emp_title'].fillna('Unknown')

# Fix int_rate — convert to percentage
df['int_rate'] = df['int_rate'] * 100

# Add Good Loan / Bad Loan column
df['loan_category'] = df['loan_status'].apply(
    lambda x: 'Good Loan' if x in ['Fully Paid', 'Current'] else 'Bad Loan'
)

# Extract month and year from issue_date
df['issue_month'] = df['issue_date'].dt.month
df['issue_year'] = df['issue_date'].dt.year
df['issue_month_name'] = df['issue_date'].dt.strftime('%B')

# Verify
print("Missing values after fix:")
print(df.isnull().sum())
print("\nNew columns added:", ['loan_category', 'issue_month', 'issue_year', 'issue_month_name'])
print("\nSample loan categories:")
print(df['loan_category'].value_counts())

# Key business statistics
print("=" * 50)
print("BANK LOAN DASHBOARD - KEY METRICS")
print("=" * 50)

print(f"\nTotal Applications     : {len(df):,}")
print(f"Total Funded Amount    : ${df['loan_amount'].sum():,.0f}")
print(f"Total Amount Received  : ${df['total_payment'].sum():,.0f}")
print(f"Avg Interest Rate      : {df['int_rate'].mean():.2f}%")
print(f"Avg DTI                : {df['dti'].mean()*100:.2f}%")
print(f"Avg Loan Amount        : ${df['loan_amount'].mean():,.0f}")

print("\n--- GOOD LOAN vs BAD LOAN ---")
print(f"Good Loans : {df[df['loan_category']=='Good Loan'].shape[0]:,} ({df[df['loan_category']=='Good Loan'].shape[0]/len(df)*100:.1f}%)")
print(f"Bad Loans  : {df[df['loan_category']=='Bad Loan'].shape[0]:,} ({df[df['loan_category']=='Bad Loan'].shape[0]/len(df)*100:.1f}%)")

print("\n--- LOAN STATUS BREAKDOWN ---")
print(df['loan_status'].value_counts())

fig, axes = plt.subplots(1, 2, figsize=(14, 6))
fig.suptitle('Good Loan vs Bad Loan Analysis', fontsize=16, fontweight='bold')

# Pie chart
colors = ['#2ecc71', '#e74c3c']
axes[0].pie(
    df['loan_category'].value_counts(),
    labels=['Good Loan', 'Bad Loan'],
    autopct='%1.1f%%',
    colors=colors,
    startangle=90
)
axes[0].set_title('Loan Category Distribution')

# Bar chart — funded amount by category
category_amount = df.groupby('loan_category')['loan_amount'].sum() / 1e6
axes[1].bar(category_amount.index, category_amount.values, color=colors)
axes[1].set_title('Total Funded Amount by Category (Millions)')
axes[1].set_ylabel('Amount ($ Millions)')
for i, v in enumerate(category_amount.values):
    axes[1].text(i, v + 1, f'${v:.1f}M', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('good_vs_bad_loan.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

# Monthly trend analysis
monthly = df.groupby(['issue_month', 'issue_month_name']).agg(
    total_applications=('id', 'count'),
    total_funded=('loan_amount', 'sum'),
    total_received=('total_payment', 'sum')
).reset_index().sort_values('issue_month')

fig, axes = plt.subplots(2, 1, figsize=(14, 10))
fig.suptitle('Monthly Loan Trends - 2021', fontsize=16, fontweight='bold')

# Applications trend
axes[0].plot(monthly['issue_month_name'], monthly['total_applications'],
             marker='o', color='#3498db', linewidth=2.5, markersize=8)
axes[0].fill_between(range(len(monthly)), monthly['total_applications'], alpha=0.3, color='#3498db')
axes[0].set_title('Monthly Loan Applications')
axes[0].set_ylabel('Number of Applications')
axes[0].set_xticks(range(len(monthly)))
axes[0].set_xticklabels(monthly['issue_month_name'], rotation=45)
for i, v in enumerate(monthly['total_applications']):
    axes[0].text(i, v + 10, str(v), ha='center', fontsize=9)

# Funded vs Received
x = range(len(monthly))
width = 0.35
axes[1].bar([i - width/2 for i in x], monthly['total_funded']/1e6,
            width, label='Funded', color='#e74c3c')
axes[1].bar([i + width/2 for i in x], monthly['total_received']/1e6,
            width, label='Received', color='#2ecc71')
axes[1].set_title('Monthly Funded vs Received (Millions)')
axes[1].set_ylabel('Amount ($ Millions)')
axes[1].set_xticks(list(x))
axes[1].set_xticklabels(monthly['issue_month_name'], rotation=45)
axes[1].legend()

plt.tight_layout()
plt.savefig('monthly_trend.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

fig, axes = plt.subplots(2, 1, figsize=(14, 12))
fig.suptitle('Loan Purpose & Grade Analysis', fontsize=16, fontweight='bold')

# Top purposes
purpose_data = df.groupby('purpose')['id'].count().sort_values(ascending=True)
colors_purpose = ['#e74c3c' if x == purpose_data.max() else '#3498db' for x in purpose_data.values]
axes[0].barh(purpose_data.index, purpose_data.values, color=colors_purpose)
axes[0].set_title('Loan Applications by Purpose')
axes[0].set_xlabel('Number of Applications')
for i, v in enumerate(purpose_data.values):
    axes[0].text(v + 50, i, str(v), va='center', fontsize=9)

# Grade breakdown
grade_data = df.groupby('grade').agg(
    total=('id', 'count'),
    bad_loans=('loan_category', lambda x: (x == 'Bad Loan').sum())
).reset_index()
grade_data['bad_loan_pct'] = round(grade_data['bad_loans'] / grade_data['total'] * 100, 1)

x = range(len(grade_data))
axes[1].bar(x, grade_data['total'], color='#3498db', label='Total Applications')
ax2 = axes[1].twinx()
ax2.plot(x, grade_data['bad_loan_pct'], color='#e74c3c',
         marker='o', linewidth=2.5, markersize=8, label='Bad Loan %')
axes[1].set_title('Loan Grade — Volume vs Bad Loan %')
axes[1].set_xticks(list(x))
axes[1].set_xticklabels(grade_data['grade'])
axes[1].set_ylabel('Total Applications', color='#3498db')
ax2.set_ylabel('Bad Loan %', color='#e74c3c')
axes[1].legend(loc='upper left')
ax2.legend(loc='upper right')

plt.tight_layout()
plt.savefig('purpose_grade_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle('Financial Distribution Analysis', fontsize=16, fontweight='bold')

# Interest rate distribution
axes[0,0].hist(df['int_rate'], bins=30, color='#3498db', edgecolor='white')
axes[0,0].set_title('Interest Rate Distribution')
axes[0,0].set_xlabel('Interest Rate %')
axes[0,0].set_ylabel('Count')
axes[0,0].axvline(df['int_rate'].mean(), color='red', linestyle='--', label=f'Mean: {df["int_rate"].mean():.1f}%')
axes[0,0].legend()

# Loan amount distribution
axes[0,1].hist(df['loan_amount'], bins=30, color='#2ecc71', edgecolor='white')
axes[0,1].set_title('Loan Amount Distribution')
axes[0,1].set_xlabel('Loan Amount ($)')
axes[0,1].set_ylabel('Count')
axes[0,1].axvline(df['loan_amount'].mean(), color='red', linestyle='--', label=f'Mean: ${df["loan_amount"].mean():,.0f}')
axes[0,1].legend()

# Interest rate by grade
grade_int = df.groupby('grade')['int_rate'].mean()
axes[1,0].bar(grade_int.index, grade_int.values, color='#e74c3c')
axes[1,0].set_title('Avg Interest Rate by Grade')
axes[1,0].set_xlabel('Grade')
axes[1,0].set_ylabel('Avg Interest Rate %')
for i, v in enumerate(grade_int.values):
    axes[1,0].text(i, v + 0.2, f'{v:.1f}%', ha='center', fontsize=9)

# Loan amount by purpose top 5
top5_purpose = df.groupby('purpose')['loan_amount'].mean().sort_values(ascending=False).head(5)
axes[1,1].bar(top5_purpose.index, top5_purpose.values, color='#9b59b6')
axes[1,1].set_title('Avg Loan Amount - Top 5 Purposes')
axes[1,1].set_xlabel('Purpose')
axes[1,1].set_ylabel('Avg Loan Amount ($)')
axes[1,1].tick_params(axis='x', rotation=30)
for i, v in enumerate(top5_purpose.values):
    axes[1,1].text(i, v + 100, f'${v:,.0f}', ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('financial_distribution.png', dpi=150, bbox_inches='tight')
plt.show()
print("Chart saved!")

# Save cleaned data to CSV
df.to_csv('financial_loan_clean.csv', index=False)
print("Clean file saved!")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())